#!/usr/bin/env python3
"""
Work out what it costs to change each key, by finding who reads it.

    scripts/classify-apply.py <extracted-rootfs> schema/keys.tsv > schema/consumers.tsv

The answer is derived, not guessed. Every key is searched for across the boot
scripts and then across the binaries and libraries, and the class follows from
where it turns up:

  restart:omci  /etc/runomci.sh reads it, so restarting omci_app rebuilds the
                command line from it. Measured at about six seconds, with an
                established PPPoE session surviving.
  reboot        only a boot script reads it, and nothing re-runs those.
  unknown       referenced inside a binary, or nowhere at all. A binary
                reference says nothing about WHEN it is read, so this stays
                unknown rather than being guessed at — the UI tells the user to
                assume a reboot, which is the safe reading.

`readers` is emitted regardless, because "which program cares about this key"
is useful even when the timing is not known.
"""
import os
import re
import subprocess
import sys

# Only real scripts, and only ones that run at boot. `bin/startup` is an ELF
# binary despite the name, and treating it as a script classified PON_LED_SPEC
# as "reboot" on no evidence at all.
BOOT_SCRIPTS = ("etc/init.d/", "etc/insdrv.sh", "etc/runsdk.sh",
                "etc/runlansds.sh", "etc/scripts/insert_europa.sh",
                "etc/runoam.sh", "etc/runigmp.sh")


def readers_of(root, key):
    """Files under root mentioning the key. grep -l over text and binaries."""
    out = []
    for sub in ("etc", "bin", "lib", "sbin", "usr"):
        d = os.path.join(root, sub)
        if not os.path.isdir(d):
            continue
        # -w, not a plain substring: the table field "VID" otherwise matches
        # inside VLAN_MANU_TAG_VID and classified SW_PORT_TBL[*].VID as
        # restart:omci on the strength of a different key entirely.
        r = subprocess.run(["grep", "-rlawF", key, d],
                           capture_output=True, text=True)
        out += [p[len(root):].lstrip("/") for p in r.stdout.split("\n") if p]
    return sorted(set(out))


def classify(readers):
    if any(p.endswith("etc/runomci.sh") for p in readers):
        return "restart:omci"
    if any(p.startswith(BOOT_SCRIPTS) for p in readers):
        return "reboot"
    return "unknown"


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    root, schema = sys.argv[1].rstrip("/"), sys.argv[2]

    names = []
    for line in open(schema, encoding="utf-8"):
        if line.startswith("#") or line.startswith("name\t"):
            continue
        n = line.split("\t")[0].strip()
        if n:
            names.append(n)

    print("# generated by scripts/classify-apply.py -- do not hand-edit.")
    print("\t".join(["name", "apply", "readers"]))
    for n in names:
        # Table rows are addressed TBL[i].Field; search for the field itself,
        # since the index is ours and never appears in a binary.
        # A table row is addressed TBL[i].Field here, but only the field name
        # appears in the firmware. Short field names like "VID" are why the
        # search is word-anchored.
        needle = re.sub(r"^.*\]\.", "", n)
        rs = readers_of(root, needle)
        print("\t".join([n, classify(rs), ",".join(rs[:6])]))


if __name__ == "__main__":
    main()
