#!/usr/bin/env python3
"""
Generate the config schema from a device's own `flash all` output.

The schema is the whole point of this UI: the browser renders forms from it
generically, so adding a key is a data change rather than a new handler. That
only works if the schema is derived from the device instead of typed by hand.

    ssh admin@<stick> '/etc/scripts/flash all cs' > cs.xml
    ssh admin@<stick> '/etc/scripts/flash all hs' > hs.xml
    scripts/gen-schema.py cs.xml hs.xml runomci.sh > schema/keys.tsv

Columns: name, store, address, section, type, apply, writable

`type` is inferred from the current value and is a starting point, not an
authority — a key holding "0" is indistinguishable from a bool, an enum and an
int. Correct it by hand; the file is checked in for exactly that reason.

`apply` says what it costs to change the key. Only `restart:omci` is derived
here, and mechanically: every key `runomci.sh` reads is by construction applied
by restarting omci_app. Everything else is `unknown` until someone traces its
consumer, which is honest and keeps the UI from promising a cheap apply it
cannot deliver.
"""
import re
import sys

# Never writable, whatever anything else says. A wrong SerDes mode takes out
# telnet, ssh, the web UI and the exporter at once, because every one of them
# arrives over that link; what is left is a serial console behind soldered UART
# pads.
REFUSED = {"LAN_SDS_MODE", "LAN_SPEED_MODE", "FIBER_MODE"}

# Lose these and the OLT stops authenticating the ONU.
IDENTITY = {
    "GPON_SN", "PON_VENDOR_ID", "MAC_KEY", "ELAN_MAC_ADDR", "GPON_ONU_MODEL",
    "PON_MODE", "GPON_PLOAM_PASSWD", "GPON_PLOAM_FORMAT", "WLAN_MAC_ADDR",
}

SECTIONS = [
    ("GPON_", "gpon"), ("PON_", "gpon"), ("OMCI_", "omci"), ("EPON_", "epon"),
    ("VLAN_", "vlan"), ("LAN_", "lan"), ("DNS", "lan"), ("DHCP", "dhcp"),
    ("PPP", "wan"), ("WAN_", "wan"), ("IGMP", "multicast"), ("MCAST", "multicast"),
    ("SUSER_", "accounts"), ("USER_", "accounts"), ("E8BDUSER_", "accounts"),
    ("SUPER_", "accounts"), ("TR069", "tr069"), ("CWMP", "tr069"),
    ("HW_", "hardware"), ("RTK_", "hardware"), ("SW_", "switch"),
    ("MAC_", "hardware"), ("ELAN_", "hardware"), ("WLAN_", "hardware"),
]


def section_of(name):
    for prefix, sect in SECTIONS:
        if name.startswith(prefix):
            return sect
    return "other"


def type_of(value):
    if value == "":
        return "string"
    if re.fullmatch(r"\d+\.\d+\.\d+\.\d+", value):
        return "ipv4"
    if re.fullmatch(r"[0-9a-fA-F]{12}", value):
        return "mac"
    if re.fullmatch(r"[0-9a-fA-F]{32}", value):
        return "hex32"
    if re.fullmatch(r"\d+", value):
        return "int"
    return "string"


def parse(path, store):
    """Yield (name, address, value) for scalars and indexed table rows."""
    text = open(path, encoding="utf-8", errors="replace").read()
    out = []
    table = None
    index = None
    for line in text.splitlines():
        d = re.search(r'<Dir Name="([^"]+)">(?:\s*<!--index=(\d+)-->)?', line)
        if d:
            name = d.group(1)
            if name in ("MIB_TABLE", "HW_MIB_TABLE"):
                table, index = None, None
            else:
                table, index = name, d.group(2)
            continue
        v = re.search(r'<Value Name="([^"]*)" Value="([^"]*)"', line)
        if not v:
            continue
        key, value = v.group(1), v.group(2)
        if table:
            # Verified addressing: TBL.<index>.<field>
            if index is None:
                continue
            # Keep the device's literal key name, spaces included. It has to
            # round-trip to `xmlconfig -g/-s`, and it is what the daemon emits,
            # so any prettifying here shows up as schema drift instead.
            out.append((f"{table}[{index}].{key}",
                        f"{table}.{index}.{key}", value, store, table))
        else:
            out.append((key, key, value, store, None))
    return out


def main():
    if len(sys.argv) < 4:
        sys.exit(__doc__)
    cs, hs, runomci = sys.argv[1], sys.argv[2], sys.argv[3]

    omci_keys = set(
        m.group(1)
        for m in re.finditer(r'(?:mib|flash) get ([A-Z_0-9]+)',
                             open(runomci, encoding="utf-8", errors="replace").read())
    )

    rows = parse(cs, "cs") + parse(hs, "hs")

    print("# generated by scripts/gen-schema.py -- edit `type` and `apply` by hand,")
    print("# but regenerate rather than hand-adding keys. See the drift test.")
    print("\t".join(["name", "store", "address", "section", "type", "apply", "writable"]))
    seen = set()
    for name, address, value, store, table in rows:
        if name in seen:
            continue
        seen.add(name)
        base = name.split("[")[0]
        if base in REFUSED:
            writable = "never"
        elif base in IDENTITY:
            writable = "identity"
        else:
            writable = "yes"
        apply_ = "restart:omci" if base in omci_keys else "unknown"
        sect = "switch" if table else section_of(base)
        print("\t".join([name, store, address, sect, type_of(value), apply_, writable]))


if __name__ == "__main__":
    main()
